### ISSUE TITLE
Implement Command Spy

### ISSUE THREAD

**Issue by lokka30** [ArcanePlugins/BlackWidow#4]
I'd like to merge the functionality of [BetterCommandSpy](https://github.com/ArcanePlugins/BetterCommandSpy) into BlackWidow. I don't have any further ideas for functionality or anything else at the moment.

**Comment by ga6rielsilva** [comment]
> I'd like to merge the functionality of [BetterCommandSpy](https://github.com/ArcanePlugins/BetterCommandSpy) into BlackWidow. I don't have any further ideas for functionality or anything else at the moment.

Maybe something similar to this?
```yml
actions:
  - id: "send-message"
    msg:
      - "%prefix% You can't run that command."
  - id: "warn-message"
    msg:
      - "%prefix% %player% tried to run %command%."
```
